### ISSUE TITLE
"Download" and "Upload" column is missing in Process Table

### ISSUE THREAD

**Issue by Universebenzene** [zvova7890/ksysguard6#4]
I installed ksysguard6 from [AUR](https://aur.archlinux.org/packages/ksysguard6-git) and noticed that Download and Upload columns are missing in Process Table. Did I miss any build dependencies or do I need more options for compiling?

**Comment by zvova7890** [comment]
Likely it was a plugin that isn't supported (yet)

**Comment by Universebenzene** [comment]
> Likely it was a plugin that isn't supported (yet)

So this was an internal plugin in ksysgard 5 and removed in 6? I used to install version 5 in several distros and always see the two columns available.

**Comment by zvova7890** [comment]
Correct. Plugins are disabled due to some problems, and I haven't paid much attention to it yet.

**Comment by jas0n098** [comment]
The issue with plugins seems to stem from processcore now being static instead of shared.
1. It causes plugins to fail to build without -fPIC
2. KPluginFactory rejects plugins with a cryptic error about not being able to instantiate the plugin classes when processcore (and the plugins) are built with -fPIC

Changing processcore back to building as shared library, plugin build errors are fixed and they are able to load successfully. I tested this with the network plugin and KSysGuard was able to show Download/Upload per process again.
The drawback to this is that it will obviously conflict with system libksysguard, which is probably why processcore was made static in the first place. In the end, there are probably a bunch of other approaches one could take here to fix them but I hope at least some of this was helpful

**Comment by zvova7890** [comment]
@jas0n098, thanks for the details! Maybe we can just rename it?

I will look into this when I have a chance.

Also, @jas0n098, if you have a working prototype, feel free to send an MR.

**Comment by Universebenzene** [comment]
Still doesn't get these two volumes in [AUR](https://aur.archlinux.org/packages/ksysguard6-git) build (built with f98ae6e), don't know why😢

**Comment by zvova7890** [comment]
> Still doesn't get these two volumes in [AUR](https://aur.archlinux.org/packages/ksysguard6-git) build (built with [f98ae6e](https://github.com/zvova7890/ksysguard6/commit/f98ae6e7b1046f018abd4737fd63b6cbc357f5a2)), don't know why😢

Try to remove/rename ~/.local/share/ksysguard/ directory

**Comment by Universebenzene** [comment]
> > Still doesn't get these two volumes in [AUR](https://aur.archlinux.org/packages/ksysguard6-git) build (built with [f98ae6e](https://github.com/zvova7890/ksysguard6/commit/f98ae6e7b1046f018abd4737fd63b6cbc357f5a2)), don't know why😢
> 
> Try to remove/rename ~/.local/share/ksysguard/ directory

Fixed. Thanks!😃
